### ISSUE TITLE
Official instance just died

### ISSUE THREAD

**Issue by wizard-28** [THEGOLDENPRO/aghpb_api_rw#14]
Thank you for creating and maintaining this project.

I wanted to bring to your attention that the official instance has just gone offline.

![image](https://github.com/THEGOLDENPRO/aghpb_api/assets/49679481/87d31408-ec44-4aa8-b1d5-314e44c79487)

**Comment by THEGOLDENPRO** [comment]
Thank you for alerting me. It's back up now, just did a little mistake. <img width="60px" src="https://yunikonureshii.wordpress.com/wp-content/uploads/2019/02/gomen.gif">
