### ISSUE TITLE
Caching Books for faster Startup

### ISSUE THREAD

**Issue by ananasmoe** [THEGOLDENPRO/aghpb_api_rw#7]
Cache Books that already were added, would save time

**Comment by THEGOLDENPRO** [comment]
yeah, I actually was planning to add something like this to my backlog for aghpb. I'll work on this soon.

**Comment by THEGOLDENPRO** [comment]
~~*but in the meantime get a faster computer*~~

**Comment by THEGOLDENPRO** [comment]
# soon™
@r3tr0ananas currently working on caching in v1.4❗

![image](https://github.com/THEGOLDENPRO/aghpb_api/assets/66202304/b8e09beb-fd86-4c65-985b-a2e974a7a85a)
